//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapyrusClient.Resources.Ui.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Home_hu_HU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home_hu_HU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PapyrusClient.Resources.Ui.Pages.Home.hu-HU", typeof(Home_hu_HU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fájl.
        /// </summary>
        internal static string DataGridFileTitle {
            get {
                return ResourceManager.GetString("DataGridFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt a fájlok feldolgozás során. További részletekért kérlek, nyisd meg a konzolt.
        ///.
        /// </summary>
        internal static string FilesProcessingError {
            get {
                return ResourceManager.GetString("FilesProcessingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legfeljebb {0} fájl tölthető be egyszerre..
        /// </summary>
        internal static string InputFileMaximumFilesAllowedPerLoad {
            get {
                return ResourceManager.GetString("InputFileMaximumFilesAllowedPerLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egyszerre csak {0} fájlt tölthetsz be..
        /// </summary>
        internal static string InputFileMaximumFilesExceeded {
            get {
                return ResourceManager.GetString("InputFileMaximumFilesExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Húzd ide az Excel-fájlokat a feltöltéshez, vagy.
        /// </summary>
        internal static string InputFilePart1 {
            get {
                return ResourceManager.GetString("InputFilePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to válaszd ki.
        /// </summary>
        internal static string InputFilePart2 {
            get {
                return ResourceManager.GetString("InputFilePart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to őket..
        /// </summary>
        internal static string InputFilePart3 {
            get {
                return ResourceManager.GetString("InputFilePart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Támogatott fájlformátumok: {0}..
        /// </summary>
        internal static string InputFileSupportedFileFormats {
            get {
                return ResourceManager.GetString("InputFileSupportedFileFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Csak az érvényes adatokkal rendelkező fájlok dolgozhatók fel..
        /// </summary>
        internal static string InvalidFilesSelected {
            get {
                return ResourceManager.GetString("InvalidFilesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A böngészőablak ideiglenesen lefagyhat a folyamat során..
        /// </summary>
        internal static string MessageBarLoadingFilesBody {
            get {
                return ResourceManager.GetString("MessageBarLoadingFilesBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fájlok Betöltése.
        /// </summary>
        internal static string MessageBarLoadingFilesTitle {
            get {
                return ResourceManager.GetString("MessageBarLoadingFilesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A böngészőablak ideiglenesen lefagyhat a folyamat során..
        /// </summary>
        internal static string MessageBarProcessingFilesBody {
            get {
                return ResourceManager.GetString("MessageBarProcessingFilesBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fájlok Feldolgozása.
        /// </summary>
        internal static string MessageBarProcessingFilesTitle {
            get {
                return ResourceManager.GetString("MessageBarProcessingFilesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem kezelt állapot: &apos;{0}&apos; a(z) &apos;{1}&apos; oldalon..
        /// </summary>
        internal static string MessageBarUnhandledStateBody {
            get {
                return ResourceManager.GetString("MessageBarUnhandledStateBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem Kezelt Státusz.
        /// </summary>
        internal static string MessageBarUnhandledStateTitle {
            get {
                return ResourceManager.GetString("MessageBarUnhandledStateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kérlek, válassz ki legalább egy fájlt.
        ///.
        /// </summary>
        internal static string NoFilesSelected {
            get {
                return ResourceManager.GetString("NoFilesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feldolgozás.
        /// </summary>
        internal static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Törlés.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
    }
}
