//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapyrusClient.Resources.Ui.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Load {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Load() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PapyrusClient.Resources.Ui.Pages.Load", typeof(Load).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string BUTTON_TEXT_DASHBOARD {
            get {
                return ResourceManager.GetString("BUTTON_TEXT_DASHBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum of {0} files allowed to load per batch..
        /// </summary>
        internal static string INPUTFILE_LABEL_MAX_LOAD_PER_BATCH {
            get {
                return ResourceManager.GetString("INPUTFILE_LABEL_MAX_LOAD_PER_BATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag the Excel file here to load or,.
        /// </summary>
        internal static string INPUTFILE_LABEL_PART1 {
            get {
                return ResourceManager.GetString("INPUTFILE_LABEL_PART1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to browser.
        /// </summary>
        internal static string INPUTFILE_LABEL_PART2 {
            get {
                return ResourceManager.GetString("INPUTFILE_LABEL_PART2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for them..
        /// </summary>
        internal static string INPUTFILE_LABEL_PART3 {
            get {
                return ResourceManager.GetString("INPUTFILE_LABEL_PART3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported file formats: {0}..
        /// </summary>
        internal static string INPUTFILE_LABEL_SUPPORTED_FORMATS {
            get {
                return ResourceManager.GetString("INPUTFILE_LABEL_SUPPORTED_FORMATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files loaded with no issues..
        /// </summary>
        internal static string MESSAGEBAR_BODY_LOADED_SCHEDULES_NO_ISSUES {
            get {
                return ResourceManager.GetString("MESSAGEBAR_BODY_LOADED_SCHEDULES_NO_ISSUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files loaded, {1} files with issues..
        /// </summary>
        internal static string MESSAGEBAR_BODY_LOADED_SCHEDULES_WITH_ISSUES {
            get {
                return ResourceManager.GetString("MESSAGEBAR_BODY_LOADED_SCHEDULES_WITH_ISSUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only load up to {0} files at a time..
        /// </summary>
        internal static string MESSAGEBAR_BODY_MAX_LOAD_PER_BATCH_REACHED {
            get {
                return ResourceManager.GetString("MESSAGEBAR_BODY_MAX_LOAD_PER_BATCH_REACHED", resourceCulture);
            }
        }
    }
}
