//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapyrusClient.Resources.Services.WorkScheduleReader {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExcelWorkScheduleReader {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExcelWorkScheduleReader() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PapyrusClient.Resources.Services.WorkScheduleReader.ExcelWorkScheduleReader", typeof(ExcelWorkScheduleReader).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file size ({0}) exceeds the maximum allowed size ({1})..
        /// </summary>
        internal static string FILE_TOO_LARGE {
            get {
                return ResourceManager.GetString("FILE_TOO_LARGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The month in year and month is invalid. Value: {0}. Please check the cell (column, row): {1}, {2}..
        /// </summary>
        internal static string INVALID_MONTH_IN_YEARMONTH {
            get {
                return ResourceManager.GetString("INVALID_MONTH_IN_YEARMONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid work schedule type. Value: {0}. Please check the cell (column, row): {1}, {2}..
        /// </summary>
        internal static string INVALID_SCHEDULE_TYPE {
            get {
                return ResourceManager.GetString("INVALID_SCHEDULE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid shift date. Value: {0}. Please check the cell (column, row): {1}, {2}..
        /// </summary>
        internal static string INVALID_SHIFT_DATE {
            get {
                return ResourceManager.GetString("INVALID_SHIFT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid shift time. Value: {0}. Please check the cell (column, row): {1}, {2}..
        /// </summary>
        internal static string INVALID_SHIFT_TIME {
            get {
                return ResourceManager.GetString("INVALID_SHIFT_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The year in year and month is invalid. Value: {0}. Please check the cell (column, row): {1}, {2}..
        /// </summary>
        internal static string INVALID_YEAR_IN_YEARMONTH {
            get {
                return ResourceManager.GetString("INVALID_YEAR_IN_YEARMONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name is missing. Please check the cell (column, row): {0}, {1}..
        /// </summary>
        internal static string MISSING_COMPANY_NAME {
            get {
                return ResourceManager.GetString("MISSING_COMPANY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extension is required..
        /// </summary>
        internal static string MISSING_FILE_EXTENSION {
            get {
                return ResourceManager.GetString("MISSING_FILE_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location address is missing. Please check the cell (column, row): {0}, {1}..
        /// </summary>
        internal static string MISSING_LOCATION_ADDRESS {
            get {
                return ResourceManager.GetString("MISSING_LOCATION_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work schedule type is missing. Please check the cell (column, row): {0}, {1}..
        /// </summary>
        internal static string MISSING_SCHEDULE_TYPE {
            get {
                return ResourceManager.GetString("MISSING_SCHEDULE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift date is missing. Please check the cell (column, row): {0}, {1}..
        /// </summary>
        internal static string MISSING_SHIFT_DATE {
            get {
                return ResourceManager.GetString("MISSING_SHIFT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee on shift is missing. Please check the cell (column, row): {0}, {1}..
        /// </summary>
        internal static string MISSING_SHIFT_EMPLOYEE {
            get {
                return ResourceManager.GetString("MISSING_SHIFT_EMPLOYEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift time is missing. Please check the cell (column, row): {0}, {1}..
        /// </summary>
        internal static string MISSING_SHIFT_TIME {
            get {
                return ResourceManager.GetString("MISSING_SHIFT_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year &amp; month is missing. Please check the cell (column, row): {0}, {1}..
        /// </summary>
        internal static string MISSING_YEARMONTH {
            get {
                return ResourceManager.GetString("MISSING_YEARMONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file extension &apos;{0}&apos; is not supported.
        ///.
        /// </summary>
        internal static string UNSUPPORTED_FILE_EXTENSION {
            get {
                return ResourceManager.GetString("UNSUPPORTED_FILE_EXTENSION", resourceCulture);
            }
        }
    }
}
