//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapyrusClient.Resources.Services.WorkScheduleReader {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WorkScheduleExcelReader_hu_HU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkScheduleExcelReader_hu_HU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PapyrusClient.Resources.Services.WorkScheduleReader.WorkScheduleExcelReader.hu-HU" +
                            "", typeof(WorkScheduleExcelReader_hu_HU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fájl túl nagy. A fájl mérete {0} bájt, amely meghaladja a {1} bájtos maximális korlátot..
        /// </summary>
        internal static string FileIsTooLarge {
            get {
                return ResourceManager.GetString("FileIsTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Érvénytelen dátum lett megadva. Kérlek, ellenőrizd a cellát (Oszlop: {0}, Sor: {1}). Érték: {2}..
        /// </summary>
        internal static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Érvénytelen fájlkiterjesztés. A fájl kiterjesztése &quot;{0}&quot; nem támogatott. Kérlek, használj érvényes kiterjesztést (például: {1})..
        /// </summary>
        internal static string InvalidFileExtension {
            get {
                return ResourceManager.GetString("InvalidFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Érvénytelen hónap szerepel az adott év és hónapban. Kérlek, ellenőrizd a cellát (Oszlop: {0}, Sor: {1}). Érték: {2}..
        /// </summary>
        internal static string InvalidMonthInYearAndMonth {
            get {
                return ResourceManager.GetString("InvalidMonthInYearAndMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Érvénytelen idő. Kérlek, használd a helyes 24 órás formátumot, vagy a folytatásjelzőt: &apos;{3}&apos;. Ellenőrizd a cellát (oszlop: {0}, sor: {1}). Érték: {2}..
        /// </summary>
        internal static string InvalidTime {
            get {
                return ResourceManager.GetString("InvalidTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Érvénytelen munkatípus. A(z) &apos;{3}&apos; munkatípus nem támogatott. Kérlek, használj egy érvényes munkatípust (pl. &apos;{4}&apos;) és frissítsd a cellát (Oszlop: {0}, Sor: {1})..
        /// </summary>
        internal static string InvalidWorkType {
            get {
                return ResourceManager.GetString("InvalidWorkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Érvénytelen év szerepel az adott év és hónapban. Kérlek, ellenőrizd a cellát (Oszlop: {0}, Sor: {1}). Érték: {2}..
        /// </summary>
        internal static string InvalidYearInYearAndMonth {
            get {
                return ResourceManager.GetString("InvalidYearInYearAndMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiányzik a cím. Kérlek, töltsd ki a hozzá tartozó cellát (Oszlop: {0}, Sor: {1})..
        /// </summary>
        internal static string MissingAddress {
            get {
                return ResourceManager.GetString("MissingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiányzik a cég neve. Kérlek, töltsd ki a hozzá tartozó cellát (Oszlop: {0}, Sor: {1})..
        /// </summary>
        internal static string MissingCompanyName {
            get {
                return ResourceManager.GetString("MissingCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiányzik a dátum. Kérlek, töltsd ki a hozzá tartozó cellát (Oszlop: {0}, Sor: {1})..
        /// </summary>
        internal static string MissingDate {
            get {
                return ResourceManager.GetString("MissingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiányzik az alkalmazott neve. Kérlek, töltsd ki a cellát (Oszlop: {0}, Sor: {1})..
        /// </summary>
        internal static string MissingEmployeeName {
            get {
                return ResourceManager.GetString("MissingEmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiányzó fájlkiterjesztés. A fájlnévnek érvényes kiterjesztést kell tartalmaznia (például: {0}) a folytatáshoz.
        /// </summary>
        internal static string MissingFileExtension {
            get {
                return ResourceManager.GetString("MissingFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiányzik a munkatípus. Kérlek, töltsd ki a hozzá tartozó cellát (Oszlop: {0}, Sor: {1})..
        /// </summary>
        internal static string MissingWorkType {
            get {
                return ResourceManager.GetString("MissingWorkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiányzik az év és a hónap. Kérlek, töltsd ki a hozzá tartozó cellát (Oszlop: {0}, Sor: {1})..
        /// </summary>
        internal static string MissingYearAndMonth {
            get {
                return ResourceManager.GetString("MissingYearAndMonth", resourceCulture);
            }
        }
    }
}
