//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapyrusClient.Resources.Services.WorkScheduleReader {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WorkScheduleExcelReader {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkScheduleExcelReader() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PapyrusClient.Resources.Services.WorkScheduleReader.WorkScheduleExcelReader", typeof(WorkScheduleExcelReader).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is too large. The file size is {0} bytes and exceeds the maximum limit of {1} bytes..
        /// </summary>
        internal static string FileIsTooLarge {
            get {
                return ResourceManager.GetString("FileIsTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date provided. Please check the cell (Column: {0}, Row: {1}). Value: {2}..
        /// </summary>
        internal static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file extension. The file&apos;s extension &quot;{0}&quot; is not supported. Please use a valid extension (e.g., {1})..
        /// </summary>
        internal static string InvalidFileExtension {
            get {
                return ResourceManager.GetString("InvalidFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid month in the provided year and month. Please check the cell (Column: {0}, Row: {1}). Value: {2}..
        /// </summary>
        internal static string InvalidMonthInYearAndMonth {
            get {
                return ResourceManager.GetString("InvalidMonthInYearAndMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid time provided. Please use the correct 24-hour format or the continuation marker &apos;{3}&apos;. Check the cell (Column: {0}, Row: {1}). Value: {2}..
        /// </summary>
        internal static string InvalidTime {
            get {
                return ResourceManager.GetString("InvalidTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid work type provided. The work type &apos;{3}&apos; is not supported. Please use a valid work type (e.g., &apos;{4}&apos;) and update the cell (Column: {0}, Row: {1})..
        /// </summary>
        internal static string InvalidWorkType {
            get {
                return ResourceManager.GetString("InvalidWorkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid year in the provided year and month. Please check the cell (Column: {0}, Row: {1}). Value: {2}..
        /// </summary>
        internal static string InvalidYearInYearAndMonth {
            get {
                return ResourceManager.GetString("InvalidYearInYearAndMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing address. Please fill it in the cell (Column: {0}, Row: {1})..
        /// </summary>
        internal static string MissingAddress {
            get {
                return ResourceManager.GetString("MissingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing company name. Please fill it in the cell (Column: {0}, Row: {1})..
        /// </summary>
        internal static string MissingCompanyName {
            get {
                return ResourceManager.GetString("MissingCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing date. Please fill it in the cell (Column: {0}, Row: {1})..
        /// </summary>
        internal static string MissingDate {
            get {
                return ResourceManager.GetString("MissingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing employee name. Please fill it in the cell (Column: {0}, Row: {1})..
        /// </summary>
        internal static string MissingEmployeeName {
            get {
                return ResourceManager.GetString("MissingEmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing file extension. Please ensure the file includes a valid extension (e.g., {0}) before proceeding..
        /// </summary>
        internal static string MissingFileExtension {
            get {
                return ResourceManager.GetString("MissingFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing work type. Please fill it in the cell (Column: {0}, Row: {1})..
        /// </summary>
        internal static string MissingWorkType {
            get {
                return ResourceManager.GetString("MissingWorkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing year and month. Please fill it in the cell (Column: {0}, Row: {1})..
        /// </summary>
        internal static string MissingYearAndMonth {
            get {
                return ResourceManager.GetString("MissingYearAndMonth", resourceCulture);
            }
        }
    }
}
