//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapyrusClient.Resources.Ui.Dialogs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FileDetailsDialog_hu_HU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileDetailsDialog_hu_HU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PapyrusClient.Resources.Ui.Dialogs.FileDetailsDialog.hu-HU", typeof(FileDetailsDialog_hu_HU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezárás.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Részletek.
        /// </summary>
        internal static string DetailsLabel {
            get {
                return ResourceManager.GetString("DetailsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az Adott Fájlról
        ///.
        /// </summary>
        internal static string DialogTitle {
            get {
                return ResourceManager.GetString("DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fájl.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fájlt nem sikerült feldolgozni..
        /// </summary>
        internal static string FileStateGeneralError {
            get {
                return ResourceManager.GetString("FileStateGeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fájl feldolgozása sikeresen megtörtént..
        /// </summary>
        internal static string FileStateOk {
            get {
                return ResourceManager.GetString("FileStateOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fájlt nem sikerült beolvasni..
        /// </summary>
        internal static string FileStateReadError {
            get {
                return ResourceManager.GetString("FileStateReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fájl ellenőrzése hibába ütközött..
        /// </summary>
        internal static string FileStateValidateError {
            get {
                return ResourceManager.GetString("FileStateValidateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azonosító.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A megadott &apos;{0}&apos; fül nem található. Ellenőrizd, hogy a fül neve helyes-e, vagy válassz egy érvényes fület..
        /// </summary>
        internal static string MessageBarTabNotFoundBody {
            get {
                return ResourceManager.GetString("MessageBarTabNotFoundBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fül Nem Található.
        /// </summary>
        internal static string MessageBarTabNotFoundTitle {
            get {
                return ResourceManager.GetString("MessageBarTabNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ez a fül egy későbbi frissítésben lesz elérhető..
        /// </summary>
        internal static string MessageBarTabNotImplementedBody {
            get {
                return ResourceManager.GetString("MessageBarTabNotImplementedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fül Még Nincs Kész.
        /// </summary>
        internal static string MessageBarTabNotImplementedTitle {
            get {
                return ResourceManager.GetString("MessageBarTabNotImplementedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beállítások.
        /// </summary>
        internal static string OptionsLabel {
            get {
                return ResourceManager.GetString("OptionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Méret (bájtban).
        /// </summary>
        internal static string SizeInBytes {
            get {
                return ResourceManager.GetString("SizeInBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Státusz.
        /// </summary>
        internal static string StatusLabel {
            get {
                return ResourceManager.GetString("StatusLabel", resourceCulture);
            }
        }
    }
}
