//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapyrusClient.Resources.Ui.Dialogs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingsDialog_hu_HU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsDialog_hu_HU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PapyrusClient.Resources.Ui.Dialogs.SettingsDialog.hu-HU", typeof(SettingsDialog_hu_HU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ünnepnapok.
        /// </summary>
        internal static string CalendarHolidaysLabel {
            get {
                return ResourceManager.GetString("CalendarHolidaysLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beállítások.
        /// </summary>
        internal static string DialogTitle {
            get {
                return ResourceManager.GetString("DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mégse.
        /// </summary>
        internal static string Discard {
            get {
                return ResourceManager.GetString("Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Használd a fenti naptárat az ünnepek kiválasztásához..
        /// </summary>
        internal static string MessageBarTabNoHolidaysSelectedBody {
            get {
                return ResourceManager.GetString("MessageBarTabNoHolidaysSelectedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincsenek Kijelölt Ünnepek
        ///.
        /// </summary>
        internal static string MessageBarTabNoHolidaysSelectedTitle {
            get {
                return ResourceManager.GetString("MessageBarTabNoHolidaysSelectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Újratöltés.
        /// </summary>
        internal static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentés.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nyelv (nem teljesen használt).
        /// </summary>
        internal static string SelectLanguageLabel {
            get {
                return ResourceManager.GetString("SelectLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sötét.
        /// </summary>
        internal static string SelectThemeDark {
            get {
                return ResourceManager.GetString("SelectThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinézet.
        /// </summary>
        internal static string SelectThemeLabel {
            get {
                return ResourceManager.GetString("SelectThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Világos.
        /// </summary>
        internal static string SelectThemeLight {
            get {
                return ResourceManager.GetString("SelectThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendszer.
        /// </summary>
        internal static string SelectThemeSystem {
            get {
                return ResourceManager.GetString("SelectThemeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ismeretlen.
        /// </summary>
        internal static string SelectThemeUnknown {
            get {
                return ResourceManager.GetString("SelectThemeUnknown", resourceCulture);
            }
        }
    }
}
