//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapyrusClient.Resources.Ui.Dialogs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WorkScheduleViewerDialog_hu_HU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkScheduleViewerDialog_hu_HU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PapyrusClient.Resources.Ui.Dialogs.WorkScheduleViewerDialog.hu-HU", typeof(WorkScheduleViewerDialog_hu_HU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azonosító.
        /// </summary>
        internal static string DETAILS_ID {
            get {
                return ResourceManager.GetString("DETAILS_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Név.
        /// </summary>
        internal static string DETAILS_NAME {
            get {
                return ResourceManager.GetString("DETAILS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forrás.
        /// </summary>
        internal static string DETAILS_SOURCE {
            get {
                return ResourceManager.GetString("DETAILS_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fájl.
        /// </summary>
        internal static string DETAILS_SOURCE_FILE {
            get {
                return ResourceManager.GetString("DETAILS_SOURCE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ismeretlen.
        /// </summary>
        internal static string DETAILS_SOURCE_UNKNOWN {
            get {
                return ResourceManager.GetString("DETAILS_SOURCE_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Információ a munkaidő-beosztásról.
        /// </summary>
        internal static string DIALOG_TITLE {
            get {
                return ResourceManager.GetString("DIALOG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A megadott &apos;{0}&apos; fül nem található. Ellenőrizd, hogy a fül neve helyes-e, vagy válassz egy érvényes fület..
        /// </summary>
        internal static string MESSAGEBAR_BODY_NOT_FOUND {
            get {
                return ResourceManager.GetString("MESSAGEBAR_BODY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ez a fül egy későbbi frissítésben lesz elérhető..
        /// </summary>
        internal static string MESSAGEBAR_BODY_NOT_IMPLEMENTED {
            get {
                return ResourceManager.GetString("MESSAGEBAR_BODY_NOT_IMPLEMENTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fül nem található.
        /// </summary>
        internal static string MESSAGEBAR_TITLE_NOT_FOUND {
            get {
                return ResourceManager.GetString("MESSAGEBAR_TITLE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fül még nincs kész.
        /// </summary>
        internal static string MESSAGEBAR_TITLE_NOT_IMPLEMENTED {
            get {
                return ResourceManager.GetString("MESSAGEBAR_TITLE_NOT_IMPLEMENTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt a munkaidő-beosztás feldolgozása közben..
        /// </summary>
        internal static string STATUS_GENERAL_ERROR {
            get {
                return ResourceManager.GetString("STATUS_GENERAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A munkaidő-beosztás sikeresen be lett olvasva és ellenőrizve..
        /// </summary>
        internal static string STATUS_OK {
            get {
                return ResourceManager.GetString("STATUS_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olvasási hiba történt a munkaidő-beosztás feldolgozása közben..
        /// </summary>
        internal static string STATUS_READ_ERROR {
            get {
                return ResourceManager.GetString("STATUS_READ_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ellenőrzési hiba történt a munkaidő-beosztás feldolgozása közben..
        /// </summary>
        internal static string STATUS_VALIDATE_ERROR {
            get {
                return ResourceManager.GetString("STATUS_VALIDATE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Részletek.
        /// </summary>
        internal static string TAB_DETAILS {
            get {
                return ResourceManager.GetString("TAB_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szabályok.
        /// </summary>
        internal static string TAB_RULES {
            get {
                return ResourceManager.GetString("TAB_RULES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Státusz.
        /// </summary>
        internal static string TAB_STATUS {
            get {
                return ResourceManager.GetString("TAB_STATUS", resourceCulture);
            }
        }
    }
}
