//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapyrusClient.Resources.Services.WorkScheduleValidator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WorkScheduleValidator_hu_HU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkScheduleValidator_hu_HU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PapyrusClient.Resources.Services.WorkScheduleValidator.WorkScheduleValidator.hu-H" +
                            "U", typeof(WorkScheduleValidator_hu_HU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs beállítva semmilyen opció ehhez a munkarendhez..
        /// </summary>
        internal static string NoOptionsSet {
            get {
                return ResourceManager.GetString("NoOptionsSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiányzik végzésnél a folytatás jelölő az alábbi alkalmazottnál: &apos;{0}&apos;, dátum: &apos;{1}&apos;. 
        /// 
        ///Ez azért kell, mert &apos;{2}&apos; dátumon folytatás jelölővel kezdődik a műszak ugyanannál az alkalmazottnál. 
        ///
        ///Nézd át ezeket a dátumokat: &apos;{2}&apos; és &apos;{1}&apos;..
        /// </summary>
        internal static string PreviousShiftMissingEndContinuationMarker {
            get {
                return ResourceManager.GetString("PreviousShiftMissingEndContinuationMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Több folytatás jelölőt találtam végzésre ennél az alkalmazottnál: &apos;{0}&apos;, dátum: &apos;{1}&apos;. 
        ///        
        ///Nézd át ezeket a dátumokat: &apos;{2}&apos; és &apos;{1}&apos;..
        /// </summary>
        internal static string PreviousShiftMultipleEndContinuationMarkerFound {
            get {
                return ResourceManager.GetString("PreviousShiftMultipleEndContinuationMarkerFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A műszak időtartama nem lehet negatív vagy nulla. 
        ///        
        ///Részletek: {0}..
        /// </summary>
        internal static string ShiftDurationNegativeOrZero {
            get {
                return ResourceManager.GetString("ShiftDurationNegativeOrZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A teljes műszakidő &apos;{0}&apos; meghaladta a megengedett maximumot: &apos;{1}&apos;. 
        ///
        ///Nézd meg ezt a dátumot: &apos;{2}&apos;..
        /// </summary>
        internal static string ShiftExceedsMaxDurationCombinedPerDay {
            get {
                return ResourceManager.GetString("ShiftExceedsMaxDurationCombinedPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az alkalmazott &apos;{0}&apos; {1} időt rögzített, ami meghaladja az engedélyezett maximumot: &apos;{2}&apos;. 
        ///
        ///Nézd meg ezt a dátumot: &apos;{3}&apos;..
        /// </summary>
        internal static string ShiftExceedsMaxDurationPerEmployeePerDay {
            get {
                return ResourceManager.GetString("ShiftExceedsMaxDurationPerEmployeePerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rés van a műszakok között: &apos;{0}&apos; dátumán. 
        ///
        ///Részletek: 
        ///    - Előző műszak: Alkalmazott &apos;{1}&apos; {2} és {3} között 
        ///    - Következő műszak: Alkalmazott &apos;{4}&apos; {5} és {6} között 
        ///    - Rés: &apos;{7}&apos;
        ///
        ///Győződj meg róla, hogy nincsenek rések a műszakok között..
        /// </summary>
        internal static string ShiftGapDetected {
            get {
                return ResourceManager.GetString("ShiftGapDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiányzik a műszak adata a következő napokon: [{0}]..
        /// </summary>
        internal static string ShiftMissingRequiredDays {
            get {
                return ResourceManager.GetString("ShiftMissingRequiredDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Átfedés van a műszakok között: &apos;{0}&apos; dátumán. 
        ///
        ///Részletek:
        ///    - Előző műszak: Alkalmazott &apos;{1}&apos; {2} és {3} között 
        ///    - Következő műszak: Alkalmazott &apos;{4}&apos; {5} és {6} között. 
        ///
        ///Nézd át kérlek az átfedéseket..
        /// </summary>
        internal static string ShiftOverlapDetected {
            get {
                return ResourceManager.GetString("ShiftOverlapDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az egyik vagy több műszak dátuma nem az előírt hónapban van: &apos;{0}&apos;. 
        ///
        ///Nézd meg ezt a dátumot: &apos;{1}&apos;..
        /// </summary>
        internal static string ShiftsDateNotInSpecifiedMonth {
            get {
                return ResourceManager.GetString("ShiftsDateNotInSpecifiedMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az egyik vagy több műszak dátuma nem az előírt évben van: &apos;{0}&apos;. 
        ///
        ///Nézd meg ezt a dátumot: &apos;{1}&apos;..
        /// </summary>
        internal static string ShiftsDateNotInSpecifiedYear {
            get {
                return ResourceManager.GetString("ShiftsDateNotInSpecifiedYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most csak az operátor munkatípusnál működik a munkaidő rés-ellenőrzés..
        /// </summary>
        internal static string WorTypeGapValidationNotSupported {
            get {
                return ResourceManager.GetString("WorTypeGapValidationNotSupported", resourceCulture);
            }
        }
    }
}
