//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapyrusClient.Resources.Services.WorkScheduleValidator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WorkScheduleValidator_hu_HU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkScheduleValidator_hu_HU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PapyrusClient.Resources.Services.WorkScheduleValidator.WorkScheduleValidator.hu-H" +
                            "U", typeof(WorkScheduleValidator_hu_HU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem lehet érvényesíteni a munkaidő-beosztást, mert korábban olvasási hiba történt. 
        ///
        ///Kérlek, először oldd meg az olvasási hibát.
        ///.
        /// </summary>
        internal static string CANT_VALIDATE_BECAUSE_READ_ERROR {
            get {
                return ResourceManager.GetString("CANT_VALIDATE_BECAUSE_READ_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A teljes összeadott műszakidő &apos;{0}&apos; meghaladta a megengedett maximumot: &apos;{1}&apos;. 
        ///
        ///Kérlek, nézd meg ezen a dátumon a műszakokat: &apos;{2}&apos;..
        /// </summary>
        internal static string COMBINED_SHIFTS_DURATION_IS_GREATER_THAN_RULE {
            get {
                return ResourceManager.GetString("COMBINED_SHIFTS_DURATION_IS_GREATER_THAN_RULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az alkalmazott &apos;{0}&apos; {1} időt rögzített, ami meghaladja az engedélyezett maximumot: &apos;{2}&apos;. 
        ///
        ///Nézd meg ezt a dátumot: &apos;{3}&apos;..
        /// </summary>
        internal static string EMPLOYEE_SHIFT_DURATION_IS_GREATER_THAN_RULE {
            get {
                return ResourceManager.GetString("EMPLOYEE_SHIFT_DURATION_IS_GREATER_THAN_RULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rést találtam a műszakok között a következő napon: &apos;{0}&apos;. 
        ///
        ///- Előző műszak: &apos;{1}&apos; dolgozó, &apos;{2}&apos;-tól &apos;{3}&apos;-ig. 
        ///- Következő műszak: &apos;{4}&apos; dolgozó, &apos;{5}&apos;-től &apos;{6}&apos;-ig.
        ///- A rés hossza: &apos;{7}&apos;. 
        ///            
        ///Kérlek, nézd át a műszakokat.
        ///.
        /// </summary>
        internal static string GAP_DETECTED_BETWEEN_SHIFTS {
            get {
                return ResourceManager.GetString("GAP_DETECTED_BETWEEN_SHIFTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiányoznak műszakok a következő napokon: [{0}]..
        /// </summary>
        internal static string MISSING_REQUIRED_DATES {
            get {
                return ResourceManager.GetString("MISSING_REQUIRED_DATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Átfedés van a műszakok között &apos;{0}&apos;-n. 
        ///
        ///Előző műszak: &apos;{1}&apos; dolgozó, &apos;{2}&apos;-tól &apos;{3}&apos;-ig. 
        ///Következő műszak: &apos;{4}&apos; dolgozó, &apos;{5}&apos;-től &apos;{6}&apos;-ig. 
        ///
        ///Kérlek, nézd át a műszakok időpontját..
        /// </summary>
        internal static string OVERLAP_DETECTED_BETWEEN_SHIFTS {
            get {
                return ResourceManager.GetString("OVERLAP_DETECTED_BETWEEN_SHIFTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiányzik végzésnél a folytatás jelölő az alábbi alkalmazottnál: &apos;{0}&apos;, dátum: &apos;{1}&apos;. 
        ///    
        ///Azért kell, mert &apos;{2}&apos; dátumon folytatás jelölővel kezdődik a műszak ugyanannál az alkalmazottnál. 
        ///
        ///Kérlek, nézd át ezeket a dátumokat: &apos;{2}&apos; és &apos;{1}&apos;..
        /// </summary>
        internal static string PREVIOUS_SHIFT_MISSING_END_CONTINUATION_MARKER {
            get {
                return ResourceManager.GetString("PREVIOUS_SHIFT_MISSING_END_CONTINUATION_MARKER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Több folytatás jelölőt találtam végzésre ennél az alkalmazottnál: &apos;{0}&apos;, dátum: &apos;{1}&apos;. 
        ///
        ///Kérlek, nézd át ezeket a dátumokat: &apos;{2}&apos; és &apos;{1}&apos;..
        /// </summary>
        internal static string PREVIOUS_SHIFT_MULTIPLE_END_CONTINUATION_MARKER_FOUND {
            get {
                return ResourceManager.GetString("PREVIOUS_SHIFT_MULTIPLE_END_CONTINUATION_MARKER_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs szabály beállítva a munkaidő-beosztáshoz, ezért az érvényesítés nem folytatható. 
        ///
        ///Kérlek, rendelj hozzá szabályt.
        ///.
        /// </summary>
        internal static string RULE_NOT_SET {
            get {
                return ResourceManager.GetString("RULE_NOT_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelenleg csak az operátor munkarend típus támogatja a műszakfolytonosság ellenőrzését.
        ///.
        /// </summary>
        internal static string SHIFT_CONTINUITY_VALIDATION_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("SHIFT_CONTINUITY_VALIDATION_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A műszak hossza nem lehet negatív vagy nulla. 
        ///
        ///Részletek: {0}..
        /// </summary>
        internal static string SHIFT_DURATION_IS_NEGATIVE_OR_ZERO {
            get {
                return ResourceManager.GetString("SHIFT_DURATION_IS_NEGATIVE_OR_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A műszak(ok) dátumának hónapja nem egyezik a munkidő-beosztás hónapjával. 
        ///            
        ///A műszak(ok) hónapja: &apos;{0}&apos;. 
        ///A munkidő-beosztás hónapja: &apos;{1}&apos;. 
        ///
        ///Kérlek, ellenőrizd a következő műszak(ok) dátumát: &apos;{2}&apos;..
        /// </summary>
        internal static string SHIFTS_DATE_MONTH_NOT_MATCH_SCHEDULE_MONTH {
            get {
                return ResourceManager.GetString("SHIFTS_DATE_MONTH_NOT_MATCH_SCHEDULE_MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A műszak(ok) dátumának éve nem egyezik a munkidő-beosztás évével. 
        ///
        ///A műszak(ok) éve: &apos;{0}&apos;. 
        ///A munkidő-beosztás éve: &apos;{1}&apos;. 
        ///
        ///Kérlek, ellenőrizd a következő műszak(ok) dátumát: &apos;{2}&apos;..
        /// </summary>
        internal static string SHIFTS_DATE_YEAR_NOT_MATCH_SCHEDULE_YEAR {
            get {
                return ResourceManager.GetString("SHIFTS_DATE_YEAR_NOT_MATCH_SCHEDULE_YEAR", resourceCulture);
            }
        }
    }
}
