//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapyrusClient.Resources.Services.TimeSheetWriter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExcelTimeSheetWriter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExcelTimeSheetWriter() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PapyrusClient.Resources.Services.TimeSheetWriter.ExcelTimeSheetWriter", typeof(ExcelTimeSheetWriter).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A..
        /// </summary>
        internal static string COLUMN_AFTERNOON_PERIOD {
            get {
                return ResourceManager.GetString("COLUMN_AFTERNOON_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARR..
        /// </summary>
        internal static string COLUMN_ARRIVE {
            get {
                return ResourceManager.GetString("COLUMN_ARRIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE.
        /// </summary>
        internal static string COLUMN_DATE {
            get {
                return ResourceManager.GetString("COLUMN_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAY.
        /// </summary>
        internal static string COLUMN_DAY {
            get {
                return ResourceManager.GetString("COLUMN_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D..
        /// </summary>
        internal static string COLUMN_DAY_PERIOD {
            get {
                return ResourceManager.GetString("COLUMN_DAY_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEA..
        /// </summary>
        internal static string COLUMN_LEAVE {
            get {
                return ResourceManager.GetString("COLUMN_LEAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N..
        /// </summary>
        internal static string COLUMN_NIGHT_PERIOD {
            get {
                return ResourceManager.GetString("COLUMN_NIGHT_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE.
        /// </summary>
        internal static string COLUMN_NOTE {
            get {
                return ResourceManager.GetString("COLUMN_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUM..
        /// </summary>
        internal static string COLUMN_SUMMARY {
            get {
                return ResourceManager.GetString("COLUMN_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to actual worked hours:.
        /// </summary>
        internal static string FOOTER_ACTUAL_WORKED_HOURS {
            get {
                return ResourceManager.GetString("FOOTER_ACTUAL_WORKED_HOURS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary (in minutes):.
        /// </summary>
        internal static string FOOTER_COLUMN_SUMMARY {
            get {
                return ResourceManager.GetString("FOOTER_COLUMN_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total monthly working hours:.
        /// </summary>
        internal static string FOOTER_MONTH_WORK_TIME {
            get {
                return ResourceManager.GetString("FOOTER_MONTH_WORK_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overtime:.
        /// </summary>
        internal static string FOOTER_OVERTIME {
            get {
                return ResourceManager.GetString("FOOTER_OVERTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paid leave:.
        /// </summary>
        internal static string FOOTER_PAID_LEAVE {
            get {
                return ResourceManager.GetString("FOOTER_PAID_LEAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to worked hours on holiday(s):.
        /// </summary>
        internal static string FOOTER_WORKED_HOURS_ON_HOLIDAY {
            get {
                return ResourceManager.GetString("FOOTER_WORKED_HOURS_ON_HOLIDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timesheet.
        /// </summary>
        internal static string TIMESHEET {
            get {
                return ResourceManager.GetString("TIMESHEET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        internal static string TYPE_OPERATOR {
            get {
                return ResourceManager.GetString("TYPE_OPERATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string TYPE_UNKNOWN {
            get {
                return ResourceManager.GetString("TYPE_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOL..
        /// </summary>
        internal static string VALUE_HOLIDAY {
            get {
                return ResourceManager.GetString("VALUE_HOLIDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBD..
        /// </summary>
        internal static string VALUE_TBD {
            get {
                return ResourceManager.GetString("VALUE_TBD", resourceCulture);
            }
        }
    }
}
