//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapyrusClient.Resources.Services.TimeSheetWriter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TimeSheetExcelWriter_hu_HU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TimeSheetExcelWriter_hu_HU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PapyrusClient.Resources.Services.TimeSheetWriter.TimeSheetExcelWriter.hu-HU", typeof(TimeSheetExcelWriter_hu_HU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D..
        /// </summary>
        internal static string AfternoonPeriodColumn {
            get {
                return ResourceManager.GetString("AfternoonPeriodColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÉRK..
        /// </summary>
        internal static string ArriveColumn {
            get {
                return ResourceManager.GetString("ArriveColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DÁT..
        /// </summary>
        internal static string DateColumn {
            get {
                return ResourceManager.GetString("DateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAP.
        /// </summary>
        internal static string DayColumn {
            get {
                return ResourceManager.GetString("DayColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N..
        /// </summary>
        internal static string DayPeriodColumn {
            get {
                return ResourceManager.GetString("DayPeriodColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelenléti Ív.
        /// </summary>
        internal static string FileNamePart {
            get {
                return ResourceManager.GetString("FileNamePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to havi órák:.
        /// </summary>
        internal static string FooterMonthlyHours {
            get {
                return ResourceManager.GetString("FooterMonthlyHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megjegyzés:.
        /// </summary>
        internal static string FooterNote {
            get {
                return ResourceManager.GetString("FooterNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to túlórák:.
        /// </summary>
        internal static string FooterOvertimeHours {
            get {
                return ResourceManager.GetString("FooterOvertimeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fizetett szabadság órák:
        ///.
        /// </summary>
        internal static string FooterPaidLeaveHours {
            get {
                return ResourceManager.GetString("FooterPaidLeaveHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Összesen:.
        /// </summary>
        internal static string FooterSummary {
            get {
                return ResourceManager.GetString("FooterSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to munkaszüneti nap órák:.
        /// </summary>
        internal static string FooterWorkedHolidayHours {
            get {
                return ResourceManager.GetString("FooterWorkedHolidayHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ledolgozott órák:.
        /// </summary>
        internal static string FooterWorkedHours {
            get {
                return ResourceManager.GetString("FooterWorkedHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSZ..
        /// </summary>
        internal static string HolidayMarker {
            get {
                return ResourceManager.GetString("HolidayMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TÁV..
        /// </summary>
        internal static string LeaveColumn {
            get {
                return ResourceManager.GetString("LeaveColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É..
        /// </summary>
        internal static string NightPeriodColumn {
            get {
                return ResourceManager.GetString("NightPeriodColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEGJ..
        /// </summary>
        internal static string NoteColumn {
            get {
                return ResourceManager.GetString("NoteColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖSSZ..
        /// </summary>
        internal static string SummaryColumn {
            get {
                return ResourceManager.GetString("SummaryColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRV..
        /// </summary>
        internal static string TbdMarker {
            get {
                return ResourceManager.GetString("TbdMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operátor.
        /// </summary>
        internal static string WorkTypeOperator {
            get {
                return ResourceManager.GetString("WorkTypeOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISM.
        /// </summary>
        internal static string WorkTypeUnknown {
            get {
                return ResourceManager.GetString("WorkTypeUnknown", resourceCulture);
            }
        }
    }
}
