//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapyrusClient.Resources.Ui.Panels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DashboardPanel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DashboardPanel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PapyrusClient.Resources.Ui.Panels.DashboardPanel", typeof(DashboardPanel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holidays.
        /// </summary>
        internal static string CALENDAR_LABEL_HOLIDAYS {
            get {
                return ResourceManager.GetString("CALENDAR_LABEL_HOLIDAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        internal static string DIALOG_FOOTER_VERSION_INVALID {
            get {
                return ResourceManager.GetString("DIALOG_FOOTER_VERSION_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string DIALOG_TITLE {
            get {
                return ResourceManager.GetString("DIALOG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use the above calendar to pick holidays..
        /// </summary>
        internal static string MESSAGEBAR_BODY_NO_HOLIDAYS_SELECTED {
            get {
                return ResourceManager.GetString("MESSAGEBAR_BODY_NO_HOLIDAYS_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No holidays selected.
        /// </summary>
        internal static string MESSAGEBAR_TITLE_NO_HOLIDAYS_SELECTED {
            get {
                return ResourceManager.GetString("MESSAGEBAR_TITLE_NO_HOLIDAYS_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string NAVLINK_HOME {
            get {
                return ResourceManager.GetString("NAVLINK_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string NAVLINK_LOAD {
            get {
                return ResourceManager.GetString("NAVLINK_LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        internal static string NAVMENU_LABEL {
            get {
                return ResourceManager.GetString("NAVMENU_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string RADIO_LABEL_THEME_DARK {
            get {
                return ResourceManager.GetString("RADIO_LABEL_THEME_DARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string RADIO_LABEL_THEME_LIGHT {
            get {
                return ResourceManager.GetString("RADIO_LABEL_THEME_LIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string RADIO_LABEL_THEME_SYSTEM {
            get {
                return ResourceManager.GetString("RADIO_LABEL_THEME_SYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string RADIO_LABEL_THEME_UNKNOWN {
            get {
                return ResourceManager.GetString("RADIO_LABEL_THEME_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string RADIOGROUP_LABEL_THEME {
            get {
                return ResourceManager.GetString("RADIOGROUP_LABEL_THEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string SELECT_LABEL_LANGUAGE {
            get {
                return ResourceManager.GetString("SELECT_LABEL_LANGUAGE", resourceCulture);
            }
        }
    }
}
